[book]
authors = ["liushan"]
language = "en"
multilingual = false
src = "src"
title = "回收宝接入文档"


[build]
build-dir = "docs"
create-missing = true
use-default-preprocessors = false


[output.html]
mathjax-support = true
site-url = "/jp-doc/"
curly-quotes = true
git-repository-url = "https://github.com/hsbteam/jp-doc"
additional-css = ["book.css"]

[output.html.playpen]
editable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

